// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using System;
using System.Collections.Generic;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;

namespace GameCollector
{

    public partial class LichessUser
    {
        public class Profile2
        {
        }
    }

    public partial class LichessUser
    {
        public class Chess9602
        {

            [JsonProperty("games")]
            public int Games { get; set; }

            [JsonProperty("rating")]
            public int Rating { get; set; }

            [JsonProperty("rd")]
            public int Rd { get; set; }

            [JsonProperty("prov")]
            public bool Prov { get; set; }

            [JsonProperty("prog")]
            public int Prog { get; set; }
        }
    }

    public partial class LichessUser
    {
        public class Blitz2
        {

            [JsonProperty("games")]
            public int Games { get; set; }

            [JsonProperty("rating")]
            public int Rating { get; set; }

            [JsonProperty("rd")]
            public int Rd { get; set; }

            [JsonProperty("prov")]
            public bool Prov { get; set; }

            [JsonProperty("prog")]
            public int Prog { get; set; }
        }
    }

    public partial class LichessUser
    {
        public class KingOfTheHill2
        {

            [JsonProperty("games")]
            public int Games { get; set; }

            [JsonProperty("rating")]
            public int Rating { get; set; }

            [JsonProperty("rd")]
            public int Rd { get; set; }

            [JsonProperty("prov")]
            public bool Prov { get; set; }

            [JsonProperty("prog")]
            public int Prog { get; set; }
        }
    }

    public partial class LichessUser
    {
        public class Crazyhouse2
        {

            [JsonProperty("games")]
            public int Games { get; set; }

            [JsonProperty("rating")]
            public int Rating { get; set; }

            [JsonProperty("rd")]
            public int Rd { get; set; }

            [JsonProperty("prov")]
            public bool Prov { get; set; }

            [JsonProperty("prog")]
            public int Prog { get; set; }
        }
    }

    public partial class LichessUser
    {
        public class ThreeCheck2
        {

            [JsonProperty("games")]
            public int Games { get; set; }

            [JsonProperty("rating")]
            public int Rating { get; set; }

            [JsonProperty("rd")]
            public int Rd { get; set; }

            [JsonProperty("prov")]
            public bool Prov { get; set; }

            [JsonProperty("prog")]
            public int Prog { get; set; }
        }
    }

    public partial class LichessUser
    {
        public class Antichess2
        {

            [JsonProperty("games")]
            public int Games { get; set; }

            [JsonProperty("rating")]
            public int Rating { get; set; }

            [JsonProperty("rd")]
            public int Rd { get; set; }

            [JsonProperty("prov")]
            public bool Prov { get; set; }

            [JsonProperty("prog")]
            public int Prog { get; set; }
        }
    }

    public partial class LichessUser
    {
        public class Bullet2
        {

            [JsonProperty("games")]
            public int Games { get; set; }

            [JsonProperty("rating")]
            public int Rating { get; set; }

            [JsonProperty("rd")]
            public int Rd { get; set; }

            [JsonProperty("prov")]
            public bool Prov { get; set; }

            [JsonProperty("prog")]
            public int Prog { get; set; }
        }
    }

    public partial class LichessUser
    {
        public class Correspondence2
        {

            [JsonProperty("games")]
            public int Games { get; set; }

            [JsonProperty("rating")]
            public int Rating { get; set; }

            [JsonProperty("rd")]
            public int Rd { get; set; }

            [JsonProperty("prov")]
            public bool Prov { get; set; }

            [JsonProperty("prog")]
            public int Prog { get; set; }
        }
    }

    public partial class LichessUser
    {
        public class Horde2
        {

            [JsonProperty("games")]
            public int Games { get; set; }

            [JsonProperty("rating")]
            public int Rating { get; set; }

            [JsonProperty("rd")]
            public int Rd { get; set; }

            [JsonProperty("prov")]
            public bool Prov { get; set; }

            [JsonProperty("prog")]
            public int Prog { get; set; }
        }
    }

    public partial class LichessUser
    {
        public class Puzzle2
        {

            [JsonProperty("games")]
            public int Games { get; set; }

            [JsonProperty("rating")]
            public int Rating { get; set; }

            [JsonProperty("rd")]
            public int Rd { get; set; }

            [JsonProperty("prov")]
            public bool Prov { get; set; }

            [JsonProperty("prog")]
            public int Prog { get; set; }
        }
    }

    public partial class LichessUser
    {
        public class Atomic2
        {

            [JsonProperty("games")]
            public int Games { get; set; }

            [JsonProperty("rating")]
            public int Rating { get; set; }

            [JsonProperty("rd")]
            public int Rd { get; set; }

            [JsonProperty("prov")]
            public bool Prov { get; set; }

            [JsonProperty("prog")]
            public int Prog { get; set; }
        }
    }

    public partial class LichessUser
    {
        public class Opening2
        {

            [JsonProperty("games")]
            public int Games { get; set; }

            [JsonProperty("rating")]
            public int Rating { get; set; }

            [JsonProperty("rd")]
            public int Rd { get; set; }

            [JsonProperty("prov")]
            public bool Prov { get; set; }

            [JsonProperty("prog")]
            public int Prog { get; set; }
        }
    }

    public partial class LichessUser
    {
        public class RacingKings2
        {

            [JsonProperty("games")]
            public int Games { get; set; }

            [JsonProperty("rating")]
            public int Rating { get; set; }

            [JsonProperty("rd")]
            public int Rd { get; set; }

            [JsonProperty("prov")]
            public bool Prov { get; set; }

            [JsonProperty("prog")]
            public int Prog { get; set; }
        }
    }

    public partial class LichessUser
    {
        public class Classical2
        {

            [JsonProperty("games")]
            public int Games { get; set; }

            [JsonProperty("rating")]
            public int Rating { get; set; }

            [JsonProperty("rd")]
            public int Rd { get; set; }

            [JsonProperty("prov")]
            public bool Prov { get; set; }

            [JsonProperty("prog")]
            public int Prog { get; set; }
        }
    }

    public partial class LichessUser
    {
        public class Perfs2
        {

            [JsonProperty("chess960")]
            public Chess9602 Chess960 { get; set; }

            [JsonProperty("blitz")]
            public Blitz2 Blitz { get; set; }

            [JsonProperty("kingOfTheHill")]
            public KingOfTheHill2 KingOfTheHill { get; set; }

            [JsonProperty("crazyhouse")]
            public Crazyhouse2 Crazyhouse { get; set; }

            [JsonProperty("threeCheck")]
            public ThreeCheck2 ThreeCheck { get; set; }

            [JsonProperty("antichess")]
            public Antichess2 Antichess { get; set; }

            [JsonProperty("bullet")]
            public Bullet2 Bullet { get; set; }

            [JsonProperty("correspondence")]
            public Correspondence2 Correspondence { get; set; }

            [JsonProperty("horde")]
            public Horde2 Horde { get; set; }

            [JsonProperty("puzzle")]
            public Puzzle2 Puzzle { get; set; }

            [JsonProperty("atomic")]
            public Atomic2 Atomic { get; set; }

            [JsonProperty("opening")]
            public Opening2 Opening { get; set; }

            [JsonProperty("racingKings")]
            public RacingKings2 RacingKings { get; set; }

            [JsonProperty("classical")]
            public Classical2 Classical { get; set; }
        }
    }

    public partial class LichessUser
    {
        public class PlayTime2
        {

            [JsonProperty("total")]
            public int Total { get; set; }

            [JsonProperty("tv")]
            public int Tv { get; set; }
        }
    }

    public partial class LichessUser
    {
        public class Count2
        {

            [JsonProperty("all")]
            public int All { get; set; }

            [JsonProperty("rated")]
            public int Rated { get; set; }

            [JsonProperty("ai")]
            public int Ai { get; set; }

            [JsonProperty("draw")]
            public int Draw { get; set; }

            [JsonProperty("drawH")]
            public int DrawH { get; set; }

            [JsonProperty("loss")]
            public int Loss { get; set; }

            [JsonProperty("lossH")]
            public int LossH { get; set; }

            [JsonProperty("win")]
            public int Win { get; set; }

            [JsonProperty("winH")]
            public int WinH { get; set; }

            [JsonProperty("bookmark")]
            public int Bookmark { get; set; }

            [JsonProperty("me")]
            public int Me { get; set; }
        }
    }

    public partial class LichessUser
    {

        [JsonProperty("id")]
        public string Id { get; set; }

        [JsonProperty("username")]
        public string Username { get; set; }

        [JsonProperty("online")]
        public bool Online { get; set; }

        [JsonProperty("engine")]
        public bool Engine { get; set; }

        [JsonProperty("booster")]
        public bool Booster { get; set; }

        [JsonProperty("language")]
        public string Language { get; set; }

        [JsonProperty("profile")]
        public Profile2 Profile { get; set; }

        [JsonProperty("perfs")]
        public Perfs2 Perfs { get; set; }

        [JsonProperty("createdAt")]
        public long CreatedAt { get; set; }

        [JsonProperty("seenAt")]
        public long SeenAt { get; set; }

        [JsonProperty("playTime")]
        public PlayTime2 PlayTime { get; set; }

        [JsonProperty("url")]
        public string Url { get; set; }

        [JsonProperty("nbFollowing")]
        public int NbFollowing { get; set; }

        [JsonProperty("nbFollowers")]
        public int NbFollowers { get; set; }

        [JsonProperty("count")]
        public Count2 Count { get; set; }

        [JsonProperty("followable")]
        public bool Followable { get; set; }

        [JsonProperty("following")]
        public bool Following { get; set; }

        [JsonProperty("blocking")]
        public bool Blocking { get; set; }

        [JsonProperty("followsYou")]
        public bool FollowsYou { get; set; }
    }

}
