// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using System;
using System.Collections.Generic;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;

namespace GameCollector
{

    public partial class LichessGame
    {
        public class Variant2
        {

            [JsonProperty("key")]
            public string Key { get; set; }

            [JsonProperty("name")]
            public string Name { get; set; }

            [JsonProperty("short")]
            public string Short { get; set; }

            [JsonProperty("title")]
            public string Title { get; set; }
        }
    }

    public partial class LichessGame
    {
        public class Status2
        {

            [JsonProperty("id")]
            public int Id { get; set; }

            [JsonProperty("name")]
            public string Name { get; set; }
        }
    }

    public partial class LichessGame
    {
        public class Division2
        {

            [JsonProperty("middle")]
            public object Middle { get; set; }

            [JsonProperty("end")]
            public object End { get; set; }
        }
    }

    public partial class LichessGame
    {
        public class Game2
        {

            [JsonProperty("id")]
            public string Id { get; set; }

            [JsonProperty("variant")]
            public Variant2 Variant { get; set; }

            [JsonProperty("speed")]
            public string Speed { get; set; }

            [JsonProperty("perf")]
            public string Perf { get; set; }

            [JsonProperty("rated")]
            public bool Rated { get; set; }

            [JsonProperty("initialFen")]
            public string InitialFen { get; set; }

            [JsonProperty("fen")]
            public string Fen { get; set; }

            [JsonProperty("player")]
            public string Player { get; set; }

            [JsonProperty("winner")]
            public string Winner { get; set; }

            [JsonProperty("turns")]
            public int Turns { get; set; }

            [JsonProperty("startedAtTurn")]
            public int StartedAtTurn { get; set; }

            [JsonProperty("threefold")]
            public bool Threefold { get; set; }

            [JsonProperty("check")]
            public string Check { get; set; }

            [JsonProperty("rematch")]
            public string Rematch { get; set; }

            [JsonProperty("source")]
            public string Source { get; set; }

            [JsonProperty("status")]
            public Status2 Status { get; set; }

            [JsonProperty("createdAt")]
            public long CreatedAt { get; set; }

            [JsonProperty("moveTimes")]
            public int[] MoveTimes { get; set; }

            [JsonProperty("division")]
            public Division2 Division { get; set; }
        }
    }

    public partial class LichessGame
    {
        public class Clock2
        {

            [JsonProperty("running")]
            public bool Running { get; set; }

            [JsonProperty("initial")]
            public int Initial { get; set; }

            [JsonProperty("increment")]
            public int Increment { get; set; }

            [JsonProperty("white")]
            public double White { get; set; }

            [JsonProperty("black")]
            public double Black { get; set; }

            [JsonProperty("emerg")]
            public int Emerg { get; set; }

            [JsonProperty("moretime")]
            public int Moretime { get; set; }
        }
    }

    public partial class LichessGame
    {
        public class Profile2
        {

            [JsonProperty("country")]
            public string Country { get; set; }

            [JsonProperty("bio")]
            public string Bio { get; set; }
        }
    }

    public partial class LichessGame
    {
        public class Crazyhouse2
        {

            [JsonProperty("games")]
            public int Games { get; set; }

            [JsonProperty("rating")]
            public int Rating { get; set; }

            [JsonProperty("rd")]
            public int Rd { get; set; }

            [JsonProperty("prov")]
            public bool Prov { get; set; }

            [JsonProperty("prog")]
            public int Prog { get; set; }
        }
    }

    public partial class LichessGame
    {
        public class Perfs2
        {

            [JsonProperty("crazyhouse")]
            public Crazyhouse2 Crazyhouse { get; set; }
        }
    }

    public partial class LichessGame
    {
        public class PlayTime2
        {

            [JsonProperty("total")]
            public int Total { get; set; }

            [JsonProperty("tv")]
            public int Tv { get; set; }
        }
    }

    public partial class LichessGame
    {
        public class User2
        {

            [JsonProperty("id")]
            public string Id { get; set; }

            [JsonProperty("username")]
            public string Username { get; set; }

            [JsonProperty("title")]
            public string Title { get; set; }

            [JsonProperty("online")]
            public bool Online { get; set; }

            [JsonProperty("engine")]
            public bool Engine { get; set; }

            [JsonProperty("booster")]
            public bool Booster { get; set; }

            [JsonProperty("language")]
            public string Language { get; set; }

            [JsonProperty("profile")]
            public Profile2 Profile { get; set; }

            [JsonProperty("perfs")]
            public Perfs2 Perfs { get; set; }

            [JsonProperty("createdAt")]
            public long CreatedAt { get; set; }

            [JsonProperty("seenAt")]
            public long SeenAt { get; set; }

            [JsonProperty("playTime")]
            public PlayTime2 PlayTime { get; set; }
        }
    }

    public partial class LichessGame
    {
        public class Player2
        {

            [JsonProperty("color")]
            public string Color { get; set; }

            [JsonProperty("version")]
            public int Version { get; set; }

            [JsonProperty("spectator")]
            public bool Spectator { get; set; }

            [JsonProperty("user")]
            public User2 User { get; set; }

            [JsonProperty("rating")]
            public int Rating { get; set; }

            [JsonProperty("ratingDiff")]
            public int RatingDiff { get; set; }

            [JsonProperty("onGame")]
            public bool OnGame { get; set; }
        }
    }

    public partial class LichessGame
    {
        public class Profile3
        {
        }
    }

    public partial class LichessGame
    {
        public class Crazyhouse3
        {

            [JsonProperty("games")]
            public int Games { get; set; }

            [JsonProperty("rating")]
            public int Rating { get; set; }

            [JsonProperty("rd")]
            public int Rd { get; set; }

            [JsonProperty("prov")]
            public bool Prov { get; set; }

            [JsonProperty("prog")]
            public int Prog { get; set; }
        }
    }

    public partial class LichessGame
    {
        public class Perfs3
        {

            [JsonProperty("crazyhouse")]
            public Crazyhouse3 Crazyhouse { get; set; }
        }
    }

    public partial class LichessGame
    {
        public class PlayTime3
        {

            [JsonProperty("total")]
            public int Total { get; set; }

            [JsonProperty("tv")]
            public int Tv { get; set; }
        }
    }

    public partial class LichessGame
    {
        public class User3
        {

            [JsonProperty("id")]
            public string Id { get; set; }

            [JsonProperty("username")]
            public string Username { get; set; }

            [JsonProperty("online")]
            public bool Online { get; set; }

            [JsonProperty("engine")]
            public bool Engine { get; set; }

            [JsonProperty("booster")]
            public bool Booster { get; set; }

            [JsonProperty("language")]
            public string Language { get; set; }

            [JsonProperty("profile")]
            public Profile3 Profile { get; set; }

            [JsonProperty("perfs")]
            public Perfs3 Perfs { get; set; }

            [JsonProperty("createdAt")]
            public long CreatedAt { get; set; }

            [JsonProperty("seenAt")]
            public long SeenAt { get; set; }

            [JsonProperty("playTime")]
            public PlayTime3 PlayTime { get; set; }
        }
    }

    public partial class LichessGame
    {
        public class Opponent2
        {

            [JsonProperty("color")]
            public string Color { get; set; }

            [JsonProperty("user")]
            public User3 User { get; set; }

            [JsonProperty("rating")]
            public int Rating { get; set; }

            [JsonProperty("ratingDiff")]
            public int RatingDiff { get; set; }

            [JsonProperty("onGame")]
            public bool OnGame { get; set; }
        }
    }

    public partial class LichessGame
    {
        public class Url2
        {

            [JsonProperty("socket")]
            public string Socket { get; set; }

            [JsonProperty("round")]
            public string Round { get; set; }
        }
    }

    public partial class LichessGame
    {
        public class Pref2
        {

            [JsonProperty("animationDuration")]
            public int AnimationDuration { get; set; }

            [JsonProperty("highlight")]
            public bool Highlight { get; set; }

            [JsonProperty("coords")]
            public int Coords { get; set; }

            [JsonProperty("replay")]
            public int Replay { get; set; }

            [JsonProperty("clockTenths")]
            public int ClockTenths { get; set; }

            [JsonProperty("clockBar")]
            public bool ClockBar { get; set; }

            [JsonProperty("showCaptured")]
            public bool ShowCaptured { get; set; }
        }
    }

    public partial class LichessGame
    {
        public class Pocket
        {

            [JsonProperty("pawn")]
            public int? Pawn { get; set; }

            [JsonProperty("bishop")]
            public int? Bishop { get; set; }

            [JsonProperty("knight")]
            public int? Knight { get; set; }

            [JsonProperty("queen")]
            public int? Queen { get; set; }
        }
    }

    public partial class LichessGame
    {
        public class Crazy2
        {

            [JsonProperty("pockets")]
            public Pocket[] Pockets { get; set; }
        }
    }

    public partial class LichessGame
    {
        public class TreePart
        {

            [JsonProperty("ply")]
            public int Ply { get; set; }

            [JsonProperty("fen")]
            public string Fen { get; set; }

            [JsonProperty("crazy")]
            public Crazy2 Crazy { get; set; }

            [JsonProperty("san")]
            public string San { get; set; }

            [JsonProperty("uci")]
            public string Uci { get; set; }

            [JsonProperty("id")]
            public string Id { get; set; }

            [JsonProperty("check")]
            public bool? Check { get; set; }
        }
    }

    public partial class LichessGame
    {
        public class Data2
        {

            [JsonProperty("game")]
            public Game2 Game { get; set; }

            [JsonProperty("clock")]
            public Clock2 Clock { get; set; }

            [JsonProperty("player")]
            public Player2 Player { get; set; }

            [JsonProperty("opponent")]
            public Opponent2 Opponent { get; set; }

            [JsonProperty("orientation")]
            public string Orientation { get; set; }

            [JsonProperty("url")]
            public Url2 Url { get; set; }

            [JsonProperty("pref")]
            public Pref2 Pref { get; set; }

            [JsonProperty("treeParts")]
            public TreePart[] TreeParts { get; set; }
        }
    }

    public partial class LichessGame
    {
        public class I18n2
        {

            [JsonProperty("flipBoard")]
            public string FlipBoard { get; set; }

            [JsonProperty("gameAborted")]
            public string GameAborted { get; set; }

            [JsonProperty("checkmate")]
            public string Checkmate { get; set; }

            [JsonProperty("whiteResigned")]
            public string WhiteResigned { get; set; }

            [JsonProperty("blackResigned")]
            public string BlackResigned { get; set; }

            [JsonProperty("stalemate")]
            public string Stalemate { get; set; }

            [JsonProperty("whiteLeftTheGame")]
            public string WhiteLeftTheGame { get; set; }

            [JsonProperty("blackLeftTheGame")]
            public string BlackLeftTheGame { get; set; }

            [JsonProperty("draw")]
            public string Draw { get; set; }

            [JsonProperty("timeOut")]
            public string TimeOut { get; set; }

            [JsonProperty("playingRightNow")]
            public string PlayingRightNow { get; set; }

            [JsonProperty("whiteIsVictorious")]
            public string WhiteIsVictorious { get; set; }

            [JsonProperty("blackIsVictorious")]
            public string BlackIsVictorious { get; set; }

            [JsonProperty("kingInTheCenter")]
            public string KingInTheCenter { get; set; }

            [JsonProperty("threeChecks")]
            public string ThreeChecks { get; set; }

            [JsonProperty("variantEnding")]
            public string VariantEnding { get; set; }

            [JsonProperty("analysis")]
            public string Analysis { get; set; }

            [JsonProperty("boardEditor")]
            public string BoardEditor { get; set; }

            [JsonProperty("continueFromHere")]
            public string ContinueFromHere { get; set; }

            [JsonProperty("playWithTheMachine")]
            public string PlayWithTheMachine { get; set; }

            [JsonProperty("playWithAFriend")]
            public string PlayWithAFriend { get; set; }

            [JsonProperty("openingExplorer")]
            public string OpeningExplorer { get; set; }

            [JsonProperty("inaccuracies")]
            public string Inaccuracies { get; set; }

            [JsonProperty("mistakes")]
            public string Mistakes { get; set; }

            [JsonProperty("blunders")]
            public string Blunders { get; set; }

            [JsonProperty("averageCentipawnLoss")]
            public string AverageCentipawnLoss { get; set; }
        }
    }

    public partial class LichessGame
    {
        public class Line
        {

            [JsonProperty("u")]
            public string U { get; set; }

            [JsonProperty("t")]
            public string T { get; set; }
        }
    }

    public partial class LichessGame
    {
        public class Data3
        {

            [JsonProperty("id")]
            public string Id { get; set; }

            [JsonProperty("name")]
            public string Name { get; set; }

            [JsonProperty("lines")]
            public Line[] Lines { get; set; }

            [JsonProperty("userId")]
            public string UserId { get; set; }

            [JsonProperty("loginRequired")]
            public bool LoginRequired { get; set; }
        }
    }

    public partial class LichessGame
    {
        public class I18n3
        {

            [JsonProperty("talkInChat")]
            public string TalkInChat { get; set; }

            [JsonProperty("toggleTheChat")]
            public string ToggleTheChat { get; set; }

            [JsonProperty("notes")]
            public string Notes { get; set; }

            [JsonProperty("typePrivateNotesHere")]
            public string TypePrivateNotesHere { get; set; }
        }
    }

    public partial class LichessGame
    {
        public class Permissions2
        {
        }
    }

    public partial class LichessGame
    {
        public class Chat2
        {

            [JsonProperty("data")]
            public Data3 Data { get; set; }

            [JsonProperty("i18n")]
            public I18n3 I18n { get; set; }

            [JsonProperty("writeable")]
            public bool Writeable { get; set; }

            [JsonProperty("noteId")]
            public string NoteId { get; set; }

            [JsonProperty("kobold")]
            public bool Kobold { get; set; }

            [JsonProperty("permissions")]
            public Permissions2 Permissions { get; set; }

            [JsonProperty("timeout")]
            public bool Timeout { get; set; }

            [JsonProperty("timeoutReasons")]
            public object TimeoutReasons { get; set; }
        }
    }

    public partial class LichessGame
    {
        public class Explorer2
        {

            [JsonProperty("endpoint")]
            public string Endpoint { get; set; }

            [JsonProperty("tablebaseEndpoint")]
            public string TablebaseEndpoint { get; set; }
        }
    }

    public partial class LichessGame
    {

        [JsonProperty("data")]
        public Data2 Data { get; set; }

        [JsonProperty("i18n")]
        public I18n2 I18n { get; set; }

        [JsonProperty("userId")]
        public string UserId { get; set; }

        [JsonProperty("chat")]
        public Chat2 Chat { get; set; }

        [JsonProperty("explorer")]
        public Explorer2 Explorer { get; set; }
    }

}
