// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using System;
using System.Collections.Generic;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;

namespace GameCollector
{

    public partial class LichessGames
    {
        public class Clock2
        {

            [JsonProperty("initial")]
            public int Initial { get; set; }

            [JsonProperty("increment")]
            public int Increment { get; set; }

            [JsonProperty("totalTime")]
            public int TotalTime { get; set; }
        }
    }

    public partial class LichessGames
    {
        public class Analysis2
        {

            [JsonProperty("inaccuracy")]
            public int Inaccuracy { get; set; }

            [JsonProperty("mistake")]
            public int Mistake { get; set; }

            [JsonProperty("blunder")]
            public int Blunder { get; set; }

            [JsonProperty("acpl")]
            public int Acpl { get; set; }
        }
    }

    public partial class LichessGames
    {
        public class White2
        {

            [JsonProperty("userId")]
            public string UserId { get; set; }

            [JsonProperty("rating")]
            public int Rating { get; set; }

            [JsonProperty("ratingDiff")]
            public int RatingDiff { get; set; }

            [JsonProperty("provisional")]
            public bool? Provisional { get; set; }

            [JsonProperty("analysis")]
            public Analysis2 Analysis { get; set; }
        }
    }

    public partial class LichessGames
    {
        public class Analysis3
        {

            [JsonProperty("inaccuracy")]
            public int Inaccuracy { get; set; }

            [JsonProperty("mistake")]
            public int Mistake { get; set; }

            [JsonProperty("blunder")]
            public int Blunder { get; set; }

            [JsonProperty("acpl")]
            public int Acpl { get; set; }
        }
    }

    public partial class LichessGames
    {
        public class Black2
        {

            [JsonProperty("userId")]
            public string UserId { get; set; }

            [JsonProperty("rating")]
            public int Rating { get; set; }

            [JsonProperty("ratingDiff")]
            public int RatingDiff { get; set; }

            [JsonProperty("analysis")]
            public Analysis3 Analysis { get; set; }

            [JsonProperty("provisional")]
            public bool? Provisional { get; set; }
        }
    }

    public partial class LichessGames
    {
        public class Players2
        {

            [JsonProperty("white")]
            public White2 White { get; set; }

            [JsonProperty("black")]
            public Black2 Black { get; set; }
        }
    }

    public partial class LichessGames
    {
        public class CurrentPageResult
        {

            [JsonProperty("id")]
            public string Id { get; set; }

            [JsonProperty("rated")]
            public bool Rated { get; set; }

            [JsonProperty("variant")]
            public string Variant { get; set; }

            [JsonProperty("speed")]
            public string Speed { get; set; }

            [JsonProperty("perf")]
            public string Perf { get; set; }

            [JsonProperty("timestamp")]
            public object Timestamp { get; set; }

            [JsonProperty("turns")]
            public int Turns { get; set; }

            [JsonProperty("status")]
            public string Status { get; set; }

            [JsonProperty("clock")]
            public Clock2 Clock { get; set; }

            [JsonProperty("players")]
            public Players2 Players { get; set; }

            [JsonProperty("winner")]
            public string Winner { get; set; }

            [JsonProperty("url")]
            public string Url { get; set; }
        }
    }

    public partial class LichessGames
    {

        [JsonProperty("currentPage")]
        public int CurrentPage { get; set; }

        [JsonProperty("maxPerPage")]
        public int MaxPerPage { get; set; }

        [JsonProperty("currentPageResults")]
        public CurrentPageResult[] CurrentPageResults { get; set; }

        [JsonProperty("nbResults")]
        public int NbResults { get; set; }

        [JsonProperty("previousPage")]
        public object PreviousPage { get; set; }

        [JsonProperty("nextPage")]
        public int NextPage { get; set; }

        [JsonProperty("nbPages")]
        public int NbPages { get; set; }
    }

}
